ganesha_map = [
    'FTSP',
    'Aula Barat',
    'Teknik Sipil',
    'Fisika',
    'Ruang Serba Guna (RSG)',
    'FSRD',
    'Aula Timur',
    'LFM',
    'Seni Murni, Desain',
    'Labtek IX B - Teknik Arsitektur',
    'Labtek IX C - Teknik Geodesi',
    'Labtek IX A - Teknik Planologi',
    'Teknik Lingkungan',
    'Teknik Geodesi',
    'GKUT',
    'Labtek VII',
    'Labtek VIII',
    'Labtek V',
    'Labtek VI',
    'Lab Konversi',
    'Lab Radar',
    'GKUB',
    'Labtek II',
    'Labtek XI',
    'Labtek X',
    'Oktagon',
    'TVST',
    'Koordinator TPB',
    'Gedung Kerjasama PLN - ITB',
    'Labtek I - Teknik Geofisika, Lab Struktur',
    'Kimia',
    'Teknik Perminyakan',
    'Labtek IV - FTM, Teknik Geologi, Teknik Pertambangan',
    'Pusat Penelitian Energi',
    'LAPI',
    'Gedung Perpustakaan Pusat',
    'Pusat Peneliti antar Universitas',
    'Gedung Serba Guna (GSG)',
    'Labtek III - FTI, Teknik Industri, Matematika, Astronomi, PPPPM',
    'Pasca Sarjana, Pusat Peneliti Kepariwisataan',
    'Sarana Olahraga Ganesha (SARAGA)' 
    
]